### ISSUE TITLE
Google .PKG option

### ISSUE THREAD

**Issue by GPAEALandon** [almenscorner/recipes#1]
Can Google Chrome have a .PKG option? Google provides a .PKG, and is available as an autopkg recipe.

In my experience, the DMG installed Chrome needs a helper installed with admin privileges in order for updates to function. With Chrome 116 on the horizon bringing weekly security updates, I would very much like to keep that functionality in tact.

**Comment by almenscorner** [comment]
Google Chrome PKG recipe has been added and the [wiki page](https://github.com/almenscorner/intune-uploader/wiki/IntuneAppUploader#pkg-recipes) for PKG app type support has been updated.

**Comment by almenscorner** [comment]
Recipe added. If any issues occur with the recipe please open a new issue.
