### ISSUE TITLE
Zoom .pkg

### ISSUE THREAD

**Issue by GPAEALandon** [almenscorner/recipes#2]
Zoom is massively used by our organization, and also updated very regularly.
hansen-m and homebysix have recipes for the PKG. They just need an intune recipe.

**Comment by almenscorner** [comment]
Zoom recipe has been added and the [wiki page](https://github.com/almenscorner/intune-uploader/wiki/IntuneAppUploader#pkg-recipes) for PKG app type support has been updated.

**Comment by almenscorner** [comment]
Recipe added. If any issues occur with the recipe please open a new issue.
