### ISSUE TITLE
Zoom PKG version

### ISSUE THREAD

**Issue by GPAEALandon** [almenscorner/recipes#3]
I don't know how difficult this would be. I just used the Zoom recipe and it uploaded to Intune successfully. I noticed in the output while it ran had two different version strings pasted below. When I manually uploaded PKGs before, Intune was using the same formatting as the jamfversion. Intune uploader appears to use the regular version. Would it be difficult to use the jamfversion instead in this case? The use-case is probably pretty small, so if it is two much trouble right now I'm not worried about it.

PlistReader: Assigning value of '5.15.7.21404' to output variable 'version'
PlistReader: Assigning value of '5.15.7 (21404)' to output variable 'jamfversion'
PlistReader: Assigning value of '10.11' to output variable 'min_os_version'

**Comment by almenscorner** [comment]
Shouldn't be a big deal to change, might do it configurable in the override in that case so you can choose which version string to use

**Comment by almenscorner** [comment]
Seems like changing to the other version string (jamfversion) causes the app to be stuck in a forever "downloading" state when using it as LOB app.. what breaks if the other version string is used @GPAEALandon ?

**Comment by almenscorner** [comment]
Version string changed to `jamfversion`
